import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../blocs/auth/auth_bloc.dart';
import '../blocs/blood_pressure/blood_pressure_bloc.dart';
import '../../domain/entities/blood_pressure_reading.dart';
import '../../core/utils/health_status_calculator.dart';

class ReportsPage extends StatefulWidget {
  const ReportsPage({super.key});

  @override
  State<ReportsPage> createState() => _ReportsPageState();
}

class _ReportsPageState extends State<ReportsPage> {
  DateTime _startDate = DateTime.now().subtract(const Duration(days: 30));
  DateTime _endDate = DateTime.now();
  String _viewMode = 'list';

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  void _loadData() {
    final authState = context.read<AuthBloc>().state;
    if (authState is AuthAuthenticated) {
      context.read<BloodPressureBloc>().add(
        BloodPressureLoadRequested(
          userId: authState.user.id,
          startDate: _startDate,
          endDate: _endDate,
        ),
      );
    }
  }

  String _generateWhatsAppMessage(List<BloodPressureReading> readings) {
    if (readings.isEmpty) return 'No blood pressure readings to share.';
    
    final dateFormat = DateFormat('MMM d, yyyy h:mm a');
    final buffer = StringBuffer();
    buffer.writeln('📊 Blood Pressure Report');
    buffer.writeln('Period: ${DateFormat('MMM d').format(_startDate)} - ${DateFormat('MMM d, yyyy').format(_endDate)}');
    buffer.writeln('Total Readings: ${readings.length}');
    buffer.writeln('');
    
    // Calculate averages
    final avgSys = readings.map((r) => r.systolic).reduce((a, b) => a + b) / readings.length;
    final avgDia = readings.map((r) => r.diastolic).reduce((a, b) => a + b) / readings.length;
    buffer.writeln('Average: ${avgSys.toStringAsFixed(0)}/${avgDia.toStringAsFixed(0)} mmHg');
    buffer.writeln('');
    buffer.writeln('Latest Readings:');
    
    for (final reading in readings.take(5)) {
      final status = HealthStatusCalculator.categorize(reading.systolic, reading.diastolic);
      buffer.writeln('• ${dateFormat.format(reading.readingDate)}: ${reading.systolic}/${reading.diastolic} mmHg (${status.label})');
    }
    
    buffer.writeln('');
    buffer.writeln('Generated by BloodPulse App');
    
    return buffer.toString();
  }

  void _shareViaWhatsApp(List<BloodPressureReading> readings) {
    final message = _generateWhatsAppMessage(readings);
    Share.share(message, subject: 'Blood Pressure Report');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Reports'),
        actions: [
          IconButton(
            icon: const Icon(Icons.calendar_today),
            onPressed: _selectDateRange,
          ),
        ],
      ),
      body: BlocBuilder<BloodPressureBloc, BloodPressureState>(
        builder: (context, state) {
          if (state is BloodPressureLoading) {
            return const Center(child: CircularProgressIndicator());
          }
          
          if (state is BloodPressureLoaded) {
            if (state.readings.isEmpty) {
              return _buildEmptyState();
            }
            return SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildDateRangeSelector(),
                  const SizedBox(height: 16),
                  _buildSummaryCard(state.readings),
                  const SizedBox(height: 16),
                  _buildActionsCard(state.readings),
                  const SizedBox(height: 16),
                  _buildReadingsList(state.readings),
                ],
              ),
            );
          }
          
          return const Center(child: Text('Select a date range to generate report'));
        },
      ),
    );
  }

  Widget _buildDateRangeSelector() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('From', style: TextStyle(color: Colors.grey)),
                  Text(DateFormat('MMM d, yyyy').format(_startDate)),
                ],
              ),
            ),
            const Icon(Icons.arrow_forward),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  const Text('To', style: TextStyle(color: Colors.grey)),
                  Text(DateFormat('MMM d, yyyy').format(_endDate)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSummaryCard(List<BloodPressureReading> readings) {
    final avgSys = readings.map((r) => r.systolic).reduce((a, b) => a + b) / readings.length;
    final avgDia = readings.map((r) => r.diastolic).reduce((a, b) => a + b) / readings.length;
    final avgPulse = readings.where((r) => r.pulse != null).isEmpty
        ? 0.0
        : readings.where((r) => r.pulse != null).map((r) => r.pulse!).reduce((a, b) => a + b) / readings.where((r) => r.pulse != null).length;
    
    final latestStatus = HealthStatusCalculator.categorize(
      readings.first.systolic,
      readings.first.diastolic,
    );

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Summary',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _buildStatItem('Readings', '${readings.length}', Icons.analytics),
                _buildStatItem('Avg Sys', avgSys.toStringAsFixed(0), Icons.favorite, color: _getBpColor(avgSys.toInt())),
                _buildStatItem('Avg Dia', avgDia.toStringAsFixed(0), Icons.favorite_border, color: _getBpColor(avgDia.toInt())),
                if (avgPulse > 0)
                  _buildStatItem('Avg Pulse', '${avgPulse.toStringAsFixed(0)} bpm', Icons.speed),
              ],
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: latestStatus.color.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  Icon(Icons.info_outline, color: latestStatus.color),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'Latest: ${latestStatus.label}',
                      style: TextStyle(color: latestStatus.color, fontWeight: FontWeight.w500),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStatItem(String label, String value, IconData icon, {Color? color}) {
    return Column(
      children: [
        Icon(icon, color: color ?? Colors.grey[600]),
        const SizedBox(height: 4),
        Text(value, style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: color)),
        Text(label, style: TextStyle(color: Colors.grey[600], fontSize: 12)),
      ],
    );
  }

  Color _getBpColor(int value) {
    final status = HealthStatusCalculator.categorize(value, 80);
    return status.color;
  }

  Widget _buildActionsCard(List<BloodPressureReading> readings) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Export & Share',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () => _shareViaWhatsApp(readings),
                    icon: const Icon(Icons.share),
                    label: const Text('Share'),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text('PDF export coming soon!')),
                      );
                    },
                    icon: const Icon(Icons.picture_as_pdf),
                    label: const Text('PDF'),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildReadingsList(List<BloodPressureReading> readings) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Reading Details',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 16),
            ...readings.map((reading) {
              final status = HealthStatusCalculator.categorize(reading.systolic, reading.diastolic);
              return ListTile(
                contentPadding: EdgeInsets.zero,
                leading: Container(
                  width: 4,
                  height: 40,
                  decoration: BoxDecoration(
                    color: status.color,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
                title: Text('${reading.systolic}/${reading.diastolic} mmHg'),
                subtitle: Text(DateFormat('MMM d, yyyy h:mm a').format(reading.readingDate)),
                trailing: reading.pulse != null 
                    ? Text('${reading.pulse} bpm', style: TextStyle(color: Colors.grey[600]))
                    : null,
              );
            }),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.description, size: 64, color: Colors.grey[400]),
          const SizedBox(height: 16),
          const Text('No readings in selected period'),
          const SizedBox(height: 8),
          ElevatedButton(
            onPressed: _selectDateRange,
            child: const Text('Change Date Range'),
          ),
        ],
      ),
    );
  }

  Future<void> _selectDateRange() async {
    final picked = await showDateRangePicker(
      context: context,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
      initialDateRange: DateTimeRange(start: _startDate, end: _endDate),
    );
    
    if (picked != null) {
      setState(() {
        _startDate = picked.start;
        _endDate = picked.end;
      });
      _loadData();
    }
  }
}